#!/usr/bin/env python3
"""
Write STAT AxisValueArray, fvar named instances, and related name table entries.
"""

from __future__ import annotations

import itertools
from io import StringIO
from typing import List

from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._f_v_a_r import NamedInstance
from fontTools.ttLib.tables.otTables import AxisValue, AxisValueArray

from FontCore.core_logging_config import get_logger
from FontCore.core_nameid_allocator import AxisDef, NameIDPlan, compose_instance_name

logger = get_logger(__name__)

STAT_VERSION_12 = 0x00010002
ELIDABLE_FLAG = 0x0002


def apply_table_edits(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
    fix_fvar_default: bool = True,
) -> None:
    """
    Write all changes to the font in memory. Does not save.

    Order: name records → fvar defaults → fvar instances → STAT.
    """
    _write_name_records(font, axis_defs, plan)
    if fix_fvar_default:
        _fix_fvar_defaults(font, axis_defs)
    _write_fvar_instances(font, axis_defs, plan, elided_fallback_name)
    _write_stat(font, axis_defs, plan, elided_fallback_name)


def generate_ttx_additions(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
) -> str:
    """
    Return TTX XML for updated name, fvar, and STAT tables.

    Note: emits full post-edit table XML (not a minimal diff fragment). Suitable
    for inspection or merge-by-hand; a true additions-only export is future work.
    """
    instance_count = count_instances(axis_defs)
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by VariableFont_TableEditor -->",
        f"<!-- instances={instance_count} elided_fallback={elided_fallback_name!r} "
        f"nameIDs={plan.free_start}-{plan.free_end} -->",
        "<ttFont>",
    ]
    for tag in ("name", "fvar", "STAT"):
        if tag not in font:
            continue
        writer = StringIO()
        font[tag].toXML(writer, font)
        parts.append(writer.getvalue().rstrip())
    parts.append("</ttFont>")
    return "\n".join(parts) + "\n"


def _write_name_records(font: TTFont, axis_defs: List[AxisDef], plan: NameIDPlan) -> None:
    name_table = font["name"]
    for axis_def in axis_defs:
        for av_def in axis_def.values:
            key = (axis_def.tag, av_def.value)
            nid = plan.axis_value_ids[key]
            name_table.setName(av_def.name, nid, 3, 1, 0x0409)

    for composed_name, nid in plan.instance_ids.items():
        name_table.setName(composed_name, nid, 3, 1, 0x0409)


def _fix_fvar_defaults(font: TTFont, axis_defs: List[AxisDef]) -> None:
    if "fvar" not in font:
        return
    axis_def_by_tag = {ad.tag: ad for ad in axis_defs}
    for fvar_axis in font["fvar"].axes:
        tag = fvar_axis.axisTag
        if tag not in axis_def_by_tag:
            continue
        ad = axis_def_by_tag[tag]
        elidable_values = [av.value for av in ad.values if av.elidable]
        if not elidable_values:
            logger.warning(
                "No elidable value for fvar axis [%s]; default unchanged (%.4f)",
                tag,
                fvar_axis.defaultValue,
            )
            continue
        new_default = elidable_values[0]
        if abs(fvar_axis.defaultValue - new_default) > 0.001:
            logger.info(
                "fvar axis [%s] default %.4f → %.4f",
                tag,
                fvar_axis.defaultValue,
                new_default,
            )
            fvar_axis.defaultValue = new_default


def _write_fvar_instances(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
) -> None:
    fvar = font["fvar"]
    fvar.instances = []

    value_lists = [ad.values for ad in axis_defs]
    tag_list = [ad.tag for ad in axis_defs]

    for combo in itertools.product(*value_lists):
        coords = {tag: float(av.value) for tag, av in zip(tag_list, combo)}
        composed = compose_instance_name(combo, elided_fallback_name)

        inst = NamedInstance()
        inst.coordinates = coords
        inst.subfamilyNameID = plan.instance_ids[composed]
        inst.postscriptNameID = 0xFFFF
        fvar.instances.append(inst)


def _write_stat(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str,
) -> None:
    if "STAT" not in font:
        raise ValueError("Font has no STAT table")

    stat_table = font["STAT"].table
    if stat_table.Version < STAT_VERSION_12:
        stat_table.Version = STAT_VERSION_12

    axis_values: List[AxisValue] = []

    for axis_def in axis_defs:
        for av_def in axis_def.values:
            av = AxisValue()
            av.Format = av_def.stat_format
            av.AxisIndex = _axis_index(stat_table, axis_def.tag)
            av.Flags = ELIDABLE_FLAG if av_def.elidable else 0x0000
            av.ValueNameID = plan.axis_value_ids[(axis_def.tag, av_def.value)]

            if av_def.stat_format == 1:
                av.Value = float(av_def.value)
            elif av_def.stat_format == 2:
                if av_def.range_min is None or av_def.range_max is None:
                    raise ValueError(
                        f"Format 2 axis value {axis_def.tag}={av_def.value} "
                        "requires range_min and range_max"
                    )
                av.RangeMinValue = float(av_def.range_min)
                av.NominalValue = float(av_def.value)
                av.RangeMaxValue = float(av_def.range_max)
            elif av_def.stat_format == 3:
                av.Value = float(av_def.value)
                if av_def.linked_value is None:
                    raise ValueError(
                        f"Format 3 axis value {axis_def.tag}={av_def.value} "
                        "requires linked_value"
                    )
                av.LinkedValue = float(av_def.linked_value)
            else:
                raise ValueError(f"Unsupported STAT AxisValue format {av_def.stat_format}")

            axis_values.append(av)

    avarray = AxisValueArray()
    avarray.AxisValue = axis_values
    stat_table.AxisValueArray = avarray

    efb_nid = plan.instance_ids.get(elided_fallback_name)
    if efb_nid is None:
        efb_nid = 2
    stat_table.ElidedFallbackNameID = efb_nid


def _axis_index(stat_table, axis_tag: str) -> int:
    if not hasattr(stat_table, "DesignAxisRecord") or not stat_table.DesignAxisRecord:
        raise ValueError("STAT has no DesignAxisRecord")
    for i, ax in enumerate(stat_table.DesignAxisRecord.Axis):
        if ax.AxisTag == axis_tag:
            return i
    raise ValueError(f"Axis tag '{axis_tag}' not found in STAT DesignAxisRecord")


def count_instances(axis_defs: List[AxisDef]) -> int:
    """Total fvar instance count from axis value cartesian product."""
    if not axis_defs:
        return 0
    n = 1
    for ad in axis_defs:
        n *= len(ad.values)
    return n


def default_fix_summary(
    font: TTFont, axis_defs: List[AxisDef]
) -> List[str]:
    """Human-readable lines describing pending fvar default corrections."""
    lines: List[str] = []
    if "fvar" not in font:
        return lines
    axis_def_by_tag = {ad.tag: ad for ad in axis_defs}
    for fvar_axis in font["fvar"].axes:
        tag = fvar_axis.axisTag
        if tag not in axis_def_by_tag:
            continue
        ad = axis_def_by_tag[tag]
        elidable = [av for av in ad.values if av.elidable]
        if not elidable:
            continue
        new_default = elidable[0].value
        if abs(fvar_axis.defaultValue - new_default) > 0.001:
            lines.append(
                f"{tag} default {fvar_axis.defaultValue:g} → {new_default:g}"
            )
    return lines


__all__ = [
    "apply_table_edits",
    "generate_ttx_additions",
    "count_instances",
    "default_fix_summary",
]
